# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gene',
            name='ensembl_id',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='entrez_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='hgnc_id',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='pli_score',
            field=models.DecimalField(blank=True, decimal_places=5, default=0.1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='ucsc_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gene',
            name='vega_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transcript',
            name='ensembl_transcript_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gene',
            name='hgnc_symbol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='refseq_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
