# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0002_auto_20160928_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='pli_score',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
