# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0004_auto_20160929_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Omim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omim_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniProt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='gene',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uniprot',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.Gene'),
        ),
        migrations.AddField(
            model_name='omim',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.Gene'),
        ),
        migrations.AddField(
            model_name='alias',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genes.Gene'),
        ),
    ]
